apiVersion: v1
kind: Service
metadata:
  name: {{ include "kimai.fullname" . }}
  labels:
    {{- include "kimai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.srvport }}
      targetPort: {{ .Values.service.srvport }}
      protocol: TCP
      name: http
  selector:
    {{- include "kimai.selectorLabels" . | nindent 4 }}
